version: '1.0.0'
services:
  makereal:
    image: penbillpopo/makereal:1.0.0
    container_name: makereal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file:
      - .env
